package godin

// Re-export all core types and functions
import (
	"github.com/gideonsigilai/godin/pkg/core"
	"github.com/gideonsigilai/godin/pkg/widgets"
)

// Re-export core types
type (
	Context = core.Context
	Widget  = core.Widget
	App     = core.App
)

// Re-export core functions
var (
	New = core.New
)

// Re-export all widget types
type (
	// Layout widgets
	Container = widgets.Container
	Column    = widgets.Column
	Row       = widgets.Row
	Expanded  = widgets.Expanded
	SizedBox  = widgets.SizedBox
	Card      = widgets.Card
	AppBar    = widgets.AppBar

	// Text widgets
	Text      = widgets.Text
	TextStyle = widgets.TextStyle

	// Input widgets
	TextField       = widgets.TextField
	InputDecoration = widgets.InputDecoration
	ElevatedButton  = widgets.ElevatedButton
	FilledButton    = widgets.FilledButton
	OutlinedButton  = widgets.OutlinedButton
	IconButton      = widgets.IconButton
	Checkbox        = widgets.Checkbox

	// Display widgets
	Image           = widgets.Image
	Icon            = widgets.Icon
	IconData        = widgets.IconData
	RichText        = widgets.RichText
	Divider         = widgets.Divider
	VerticalDivider = widgets.VerticalDivider
	Spacer          = widgets.Spacer
	Opacity         = widgets.Opacity
	Visibility      = widgets.Visibility
	ClipRRect       = widgets.ClipRRect
	ClipOval        = widgets.ClipOval
	ClipPath        = widgets.ClipPath
	CircleAvatar    = widgets.CircleAvatar
	AlertDialog     = widgets.AlertDialog
	SimpleDialog    = widgets.SimpleDialog
	SnackBar        = widgets.SnackBar
	SnackBarAction  = widgets.SnackBarAction

	// Layout widgets (additional)
	Stack             = widgets.Stack
	Positioned        = widgets.Positioned
	Flexible          = widgets.Flexible
	Padding           = widgets.Padding
	Center            = widgets.Center
	Align             = widgets.Align
	Transform         = widgets.Transform
	AnimatedContainer = widgets.AnimatedContainer
	BoxConstraints    = widgets.BoxConstraints

	// Form widgets (additional)
	TextFormField            = widgets.TextFormField
	Switch                   = widgets.Switch
	Button                   = widgets.Button
	Dropdown                 = widgets.Dropdown
	DropdownOption           = widgets.DropdownOption
	Slider                   = widgets.Slider
	TextButton               = widgets.TextButton
	FloatingActionButton     = widgets.FloatingActionButton
	FocusNode                = widgets.FocusNode
	MaterialStatesController = widgets.MaterialStatesController

	// Navigation widgets
	Drawer                  = widgets.Drawer
	BottomNavigationBar     = widgets.BottomNavigationBar
	BottomNavigationBarItem = widgets.BottomNavigationBarItem
	TabController           = widgets.TabController
	TabBar                  = widgets.TabBar
	TabBarView              = widgets.TabBarView
	IconThemeData           = widgets.IconThemeData

	// Data widgets
	ListView              = widgets.ListView
	ListTile              = widgets.ListTile
	GridView              = widgets.GridView
	SingleChildScrollView = widgets.SingleChildScrollView
	PageController        = widgets.PageController
	PageView              = widgets.PageView
	CustomScrollView      = widgets.CustomScrollView
	DataTable             = widgets.DataTable

	// Interactive widgets
	Dialog      = widgets.Dialog
	BottomSheet = widgets.BottomSheet

	// State widgets
	ValueListenableBuilder   = widgets.ValueListenableBuilder
	StreamBuilder            = widgets.StreamBuilder
	FutureBuilder            = widgets.FutureBuilder
	StateBuilder             = widgets.StateBuilder
	Consumer                 = widgets.Consumer
	Provider                 = widgets.Provider
	Selector                 = widgets.Selector
	ChangeNotifierProvider   = widgets.ChangeNotifierProvider
	AnimatedBuilder          = widgets.AnimatedBuilder
	LayoutBuilderConstraints = widgets.LayoutBuilderConstraints
	LayoutBuilder            = widgets.LayoutBuilder

	// Color type
	Color = widgets.Color
)

// Color constructor function to make it work like the original
func ColorFromString(s string) Color {
	return Color(s)
}

// Re-export widget constants and functions
var (
	// Text alignment
	TextAlignLeft   = widgets.TextAlignLeft
	TextAlignCenter = widgets.TextAlignCenter
	TextAlignRight  = widgets.TextAlignRight

	// Font weights
	FontWeightNormal = widgets.FontWeightNormal
	FontWeightBold   = widgets.FontWeightBold
	FontWeightW100   = widgets.FontWeightW100
	FontWeightW200   = widgets.FontWeightW200
	FontWeightW300   = widgets.FontWeightW300
	FontWeightW400   = widgets.FontWeightW400
	FontWeightW500   = widgets.FontWeightW500
	FontWeightW600   = widgets.FontWeightW600
	FontWeightW700   = widgets.FontWeightW700
	FontWeightW800   = widgets.FontWeightW800
	FontWeightW900   = widgets.FontWeightW900

	// Alignment
	MainAxisAlignmentStart        = widgets.MainAxisAlignmentStart
	MainAxisAlignmentEnd          = widgets.MainAxisAlignmentEnd
	MainAxisAlignmentCenter       = widgets.MainAxisAlignmentCenter
	MainAxisAlignmentSpaceBetween = widgets.MainAxisAlignmentSpaceBetween
	MainAxisAlignmentSpaceAround  = widgets.MainAxisAlignmentSpaceAround
	MainAxisAlignmentSpaceEvenly  = widgets.MainAxisAlignmentSpaceEvenly
	CrossAxisAlignmentStart       = widgets.CrossAxisAlignmentStart
	CrossAxisAlignmentEnd         = widgets.CrossAxisAlignmentEnd
	CrossAxisAlignmentCenter      = widgets.CrossAxisAlignmentCenter
	CrossAxisAlignmentStretch     = widgets.CrossAxisAlignmentStretch

	// Basic Color constants
	ColorTransparent = widgets.ColorTransparent
	ColorBlack       = widgets.ColorBlack
	ColorWhite       = widgets.ColorWhite

	// Primary colors
	ColorRed        = widgets.ColorRed
	ColorGreen      = widgets.ColorGreen
	ColorBlue       = widgets.ColorBlue
	ColorYellow     = widgets.ColorYellow
	ColorOrange     = widgets.ColorOrange
	ColorPurple     = widgets.ColorPurple
	ColorGrey       = widgets.ColorGrey
	ColorCyan       = widgets.ColorCyan
	ColorPink       = widgets.ColorPink
	ColorIndigo     = widgets.ColorIndigo
	ColorTeal       = widgets.ColorTeal
	ColorLime       = widgets.ColorLime
	ColorAmber      = widgets.ColorAmber
	ColorDeepOrange = widgets.ColorDeepOrange
	ColorDeepPurple = widgets.ColorDeepPurple
	ColorLightBlue  = widgets.ColorLightBlue
	ColorLightGreen = widgets.ColorLightGreen
	ColorBrown      = widgets.ColorBrown
	ColorBlueGrey   = widgets.ColorBlueGrey

	// Red shades
	ColorRed50   = widgets.ColorRed50
	ColorRed100  = widgets.ColorRed100
	ColorRed200  = widgets.ColorRed200
	ColorRed300  = widgets.ColorRed300
	ColorRed400  = widgets.ColorRed400
	ColorRed500  = widgets.ColorRed500
	ColorRed600  = widgets.ColorRed600
	ColorRed700  = widgets.ColorRed700
	ColorRed800  = widgets.ColorRed800
	ColorRed900  = widgets.ColorRed900
	ColorRedA100 = widgets.ColorRedA100
	ColorRedA200 = widgets.ColorRedA200
	ColorRedA400 = widgets.ColorRedA400
	ColorRedA700 = widgets.ColorRedA700

	// Pink shades
	ColorPink50   = widgets.ColorPink50
	ColorPink100  = widgets.ColorPink100
	ColorPink200  = widgets.ColorPink200
	ColorPink300  = widgets.ColorPink300
	ColorPink400  = widgets.ColorPink400
	ColorPink500  = widgets.ColorPink500
	ColorPink600  = widgets.ColorPink600
	ColorPink700  = widgets.ColorPink700
	ColorPink800  = widgets.ColorPink800
	ColorPink900  = widgets.ColorPink900
	ColorPinkA100 = widgets.ColorPinkA100
	ColorPinkA200 = widgets.ColorPinkA200
	ColorPinkA400 = widgets.ColorPinkA400
	ColorPinkA700 = widgets.ColorPinkA700

	// Purple shades
	ColorPurple50   = widgets.ColorPurple50
	ColorPurple100  = widgets.ColorPurple100
	ColorPurple200  = widgets.ColorPurple200
	ColorPurple300  = widgets.ColorPurple300
	ColorPurple400  = widgets.ColorPurple400
	ColorPurple500  = widgets.ColorPurple500
	ColorPurple600  = widgets.ColorPurple600
	ColorPurple700  = widgets.ColorPurple700
	ColorPurple800  = widgets.ColorPurple800
	ColorPurple900  = widgets.ColorPurple900
	ColorPurpleA100 = widgets.ColorPurpleA100
	ColorPurpleA200 = widgets.ColorPurpleA200
	ColorPurpleA400 = widgets.ColorPurpleA400
	ColorPurpleA700 = widgets.ColorPurpleA700

	// Deep Purple shades
	ColorDeepPurple50   = widgets.ColorDeepPurple50
	ColorDeepPurple100  = widgets.ColorDeepPurple100
	ColorDeepPurple200  = widgets.ColorDeepPurple200
	ColorDeepPurple300  = widgets.ColorDeepPurple300
	ColorDeepPurple400  = widgets.ColorDeepPurple400
	ColorDeepPurple500  = widgets.ColorDeepPurple500
	ColorDeepPurple600  = widgets.ColorDeepPurple600
	ColorDeepPurple700  = widgets.ColorDeepPurple700
	ColorDeepPurple800  = widgets.ColorDeepPurple800
	ColorDeepPurple900  = widgets.ColorDeepPurple900
	ColorDeepPurpleA100 = widgets.ColorDeepPurpleA100
	ColorDeepPurpleA200 = widgets.ColorDeepPurpleA200
	ColorDeepPurpleA400 = widgets.ColorDeepPurpleA400
	ColorDeepPurpleA700 = widgets.ColorDeepPurpleA700

	// Indigo shades
	ColorIndigo50   = widgets.ColorIndigo50
	ColorIndigo100  = widgets.ColorIndigo100
	ColorIndigo200  = widgets.ColorIndigo200
	ColorIndigo300  = widgets.ColorIndigo300
	ColorIndigo400  = widgets.ColorIndigo400
	ColorIndigo500  = widgets.ColorIndigo500
	ColorIndigo600  = widgets.ColorIndigo600
	ColorIndigo700  = widgets.ColorIndigo700
	ColorIndigo800  = widgets.ColorIndigo800
	ColorIndigo900  = widgets.ColorIndigo900
	ColorIndigoA100 = widgets.ColorIndigoA100
	ColorIndigoA200 = widgets.ColorIndigoA200
	ColorIndigoA400 = widgets.ColorIndigoA400
	ColorIndigoA700 = widgets.ColorIndigoA700

	// Blue shades
	ColorBlue50   = widgets.ColorBlue50
	ColorBlue100  = widgets.ColorBlue100
	ColorBlue200  = widgets.ColorBlue200
	ColorBlue300  = widgets.ColorBlue300
	ColorBlue400  = widgets.ColorBlue400
	ColorBlue500  = widgets.ColorBlue500
	ColorBlue600  = widgets.ColorBlue600
	ColorBlue700  = widgets.ColorBlue700
	ColorBlue800  = widgets.ColorBlue800
	ColorBlue900  = widgets.ColorBlue900
	ColorBlueA100 = widgets.ColorBlueA100
	ColorBlueA200 = widgets.ColorBlueA200
	ColorBlueA400 = widgets.ColorBlueA400
	ColorBlueA700 = widgets.ColorBlueA700

	// Light Blue shades
	ColorLightBlue50   = widgets.ColorLightBlue50
	ColorLightBlue100  = widgets.ColorLightBlue100
	ColorLightBlue200  = widgets.ColorLightBlue200
	ColorLightBlue300  = widgets.ColorLightBlue300
	ColorLightBlue400  = widgets.ColorLightBlue400
	ColorLightBlue500  = widgets.ColorLightBlue500
	ColorLightBlue600  = widgets.ColorLightBlue600
	ColorLightBlue700  = widgets.ColorLightBlue700
	ColorLightBlue800  = widgets.ColorLightBlue800
	ColorLightBlue900  = widgets.ColorLightBlue900
	ColorLightBlueA100 = widgets.ColorLightBlueA100
	ColorLightBlueA200 = widgets.ColorLightBlueA200
	ColorLightBlueA400 = widgets.ColorLightBlueA400
	ColorLightBlueA700 = widgets.ColorLightBlueA700

	// Cyan shades
	ColorCyan50   = widgets.ColorCyan50
	ColorCyan100  = widgets.ColorCyan100
	ColorCyan200  = widgets.ColorCyan200
	ColorCyan300  = widgets.ColorCyan300
	ColorCyan400  = widgets.ColorCyan400
	ColorCyan500  = widgets.ColorCyan500
	ColorCyan600  = widgets.ColorCyan600
	ColorCyan700  = widgets.ColorCyan700
	ColorCyan800  = widgets.ColorCyan800
	ColorCyan900  = widgets.ColorCyan900
	ColorCyanA100 = widgets.ColorCyanA100
	ColorCyanA200 = widgets.ColorCyanA200
	ColorCyanA400 = widgets.ColorCyanA400
	ColorCyanA700 = widgets.ColorCyanA700

	// Teal shades
	ColorTeal50   = widgets.ColorTeal50
	ColorTeal100  = widgets.ColorTeal100
	ColorTeal200  = widgets.ColorTeal200
	ColorTeal300  = widgets.ColorTeal300
	ColorTeal400  = widgets.ColorTeal400
	ColorTeal500  = widgets.ColorTeal500
	ColorTeal600  = widgets.ColorTeal600
	ColorTeal700  = widgets.ColorTeal700
	ColorTeal800  = widgets.ColorTeal800
	ColorTeal900  = widgets.ColorTeal900
	ColorTealA100 = widgets.ColorTealA100
	ColorTealA200 = widgets.ColorTealA200
	ColorTealA400 = widgets.ColorTealA400
	ColorTealA700 = widgets.ColorTealA700

	// Green shades
	ColorGreen50   = widgets.ColorGreen50
	ColorGreen100  = widgets.ColorGreen100
	ColorGreen200  = widgets.ColorGreen200
	ColorGreen300  = widgets.ColorGreen300
	ColorGreen400  = widgets.ColorGreen400
	ColorGreen500  = widgets.ColorGreen500
	ColorGreen600  = widgets.ColorGreen600
	ColorGreen700  = widgets.ColorGreen700
	ColorGreen800  = widgets.ColorGreen800
	ColorGreen900  = widgets.ColorGreen900
	ColorGreenA100 = widgets.ColorGreenA100
	ColorGreenA200 = widgets.ColorGreenA200
	ColorGreenA400 = widgets.ColorGreenA400
	ColorGreenA700 = widgets.ColorGreenA700

	// Light Green shades
	ColorLightGreen50   = widgets.ColorLightGreen50
	ColorLightGreen100  = widgets.ColorLightGreen100
	ColorLightGreen200  = widgets.ColorLightGreen200
	ColorLightGreen300  = widgets.ColorLightGreen300
	ColorLightGreen400  = widgets.ColorLightGreen400
	ColorLightGreen500  = widgets.ColorLightGreen500
	ColorLightGreen600  = widgets.ColorLightGreen600
	ColorLightGreen700  = widgets.ColorLightGreen700
	ColorLightGreen800  = widgets.ColorLightGreen800
	ColorLightGreen900  = widgets.ColorLightGreen900
	ColorLightGreenA100 = widgets.ColorLightGreenA100
	ColorLightGreenA200 = widgets.ColorLightGreenA200
	ColorLightGreenA400 = widgets.ColorLightGreenA400
	ColorLightGreenA700 = widgets.ColorLightGreenA700

	// Lime shades
	ColorLime50   = widgets.ColorLime50
	ColorLime100  = widgets.ColorLime100
	ColorLime200  = widgets.ColorLime200
	ColorLime300  = widgets.ColorLime300
	ColorLime400  = widgets.ColorLime400
	ColorLime500  = widgets.ColorLime500
	ColorLime600  = widgets.ColorLime600
	ColorLime700  = widgets.ColorLime700
	ColorLime800  = widgets.ColorLime800
	ColorLime900  = widgets.ColorLime900
	ColorLimeA100 = widgets.ColorLimeA100
	ColorLimeA200 = widgets.ColorLimeA200
	ColorLimeA400 = widgets.ColorLimeA400
	ColorLimeA700 = widgets.ColorLimeA700

	// Yellow shades
	ColorYellow50   = widgets.ColorYellow50
	ColorYellow100  = widgets.ColorYellow100
	ColorYellow200  = widgets.ColorYellow200
	ColorYellow300  = widgets.ColorYellow300
	ColorYellow400  = widgets.ColorYellow400
	ColorYellow500  = widgets.ColorYellow500
	ColorYellow600  = widgets.ColorYellow600
	ColorYellow700  = widgets.ColorYellow700
	ColorYellow800  = widgets.ColorYellow800
	ColorYellow900  = widgets.ColorYellow900
	ColorYellowA100 = widgets.ColorYellowA100
	ColorYellowA200 = widgets.ColorYellowA200
	ColorYellowA400 = widgets.ColorYellowA400
	ColorYellowA700 = widgets.ColorYellowA700

	// Amber shades
	ColorAmber50   = widgets.ColorAmber50
	ColorAmber100  = widgets.ColorAmber100
	ColorAmber200  = widgets.ColorAmber200
	ColorAmber300  = widgets.ColorAmber300
	ColorAmber400  = widgets.ColorAmber400
	ColorAmber500  = widgets.ColorAmber500
	ColorAmber600  = widgets.ColorAmber600
	ColorAmber700  = widgets.ColorAmber700
	ColorAmber800  = widgets.ColorAmber800
	ColorAmber900  = widgets.ColorAmber900
	ColorAmberA100 = widgets.ColorAmberA100
	ColorAmberA200 = widgets.ColorAmberA200
	ColorAmberA400 = widgets.ColorAmberA400
	ColorAmberA700 = widgets.ColorAmberA700

	// Orange shades
	ColorOrange50   = widgets.ColorOrange50
	ColorOrange100  = widgets.ColorOrange100
	ColorOrange200  = widgets.ColorOrange200
	ColorOrange300  = widgets.ColorOrange300
	ColorOrange400  = widgets.ColorOrange400
	ColorOrange500  = widgets.ColorOrange500
	ColorOrange600  = widgets.ColorOrange600
	ColorOrange700  = widgets.ColorOrange700
	ColorOrange800  = widgets.ColorOrange800
	ColorOrange900  = widgets.ColorOrange900
	ColorOrangeA100 = widgets.ColorOrangeA100
	ColorOrangeA200 = widgets.ColorOrangeA200
	ColorOrangeA400 = widgets.ColorOrangeA400
	ColorOrangeA700 = widgets.ColorOrangeA700

	// Deep Orange shades
	ColorDeepOrange50   = widgets.ColorDeepOrange50
	ColorDeepOrange100  = widgets.ColorDeepOrange100
	ColorDeepOrange200  = widgets.ColorDeepOrange200
	ColorDeepOrange300  = widgets.ColorDeepOrange300
	ColorDeepOrange400  = widgets.ColorDeepOrange400
	ColorDeepOrange500  = widgets.ColorDeepOrange500
	ColorDeepOrange600  = widgets.ColorDeepOrange600
	ColorDeepOrange700  = widgets.ColorDeepOrange700
	ColorDeepOrange800  = widgets.ColorDeepOrange800
	ColorDeepOrange900  = widgets.ColorDeepOrange900
	ColorDeepOrangeA100 = widgets.ColorDeepOrangeA100
	ColorDeepOrangeA200 = widgets.ColorDeepOrangeA200
	ColorDeepOrangeA400 = widgets.ColorDeepOrangeA400
	ColorDeepOrangeA700 = widgets.ColorDeepOrangeA700

	// Brown shades
	ColorBrown50  = widgets.ColorBrown50
	ColorBrown100 = widgets.ColorBrown100
	ColorBrown200 = widgets.ColorBrown200
	ColorBrown300 = widgets.ColorBrown300
	ColorBrown400 = widgets.ColorBrown400
	ColorBrown500 = widgets.ColorBrown500
	ColorBrown600 = widgets.ColorBrown600
	ColorBrown700 = widgets.ColorBrown700
	ColorBrown800 = widgets.ColorBrown800
	ColorBrown900 = widgets.ColorBrown900

	// Grey shades
	ColorGrey50  = widgets.ColorGrey50
	ColorGrey100 = widgets.ColorGrey100
	ColorGrey200 = widgets.ColorGrey200
	ColorGrey300 = widgets.ColorGrey300
	ColorGrey400 = widgets.ColorGrey400
	ColorGrey500 = widgets.ColorGrey500
	ColorGrey600 = widgets.ColorGrey600
	ColorGrey700 = widgets.ColorGrey700
	ColorGrey800 = widgets.ColorGrey800
	ColorGrey900 = widgets.ColorGrey900

	// Blue Grey shades
	ColorBlueGrey50  = widgets.ColorBlueGrey50
	ColorBlueGrey100 = widgets.ColorBlueGrey100
	ColorBlueGrey200 = widgets.ColorBlueGrey200
	ColorBlueGrey300 = widgets.ColorBlueGrey300
	ColorBlueGrey400 = widgets.ColorBlueGrey400
	ColorBlueGrey500 = widgets.ColorBlueGrey500
	ColorBlueGrey600 = widgets.ColorBlueGrey600
	ColorBlueGrey700 = widgets.ColorBlueGrey700
	ColorBlueGrey800 = widgets.ColorBlueGrey800
	ColorBlueGrey900 = widgets.ColorBlueGrey900

	// CSS Named Colors
	ColorAliceBlue            = widgets.ColorAliceBlue
	ColorAntiqueWhite         = widgets.ColorAntiqueWhite
	ColorAqua                 = widgets.ColorAqua
	ColorAquamarine           = widgets.ColorAquamarine
	ColorAzure                = widgets.ColorAzure
	ColorBeige                = widgets.ColorBeige
	ColorBisque               = widgets.ColorBisque
	ColorBlanchedAlmond       = widgets.ColorBlanchedAlmond
	ColorBlueViolet           = widgets.ColorBlueViolet
	ColorBurlywood            = widgets.ColorBurlywood
	ColorCadetBlue            = widgets.ColorCadetBlue
	ColorChartreuse           = widgets.ColorChartreuse
	ColorChocolate            = widgets.ColorChocolate
	ColorCoral                = widgets.ColorCoral
	ColorCornflowerBlue       = widgets.ColorCornflowerBlue
	ColorCornsilk             = widgets.ColorCornsilk
	ColorCrimson              = widgets.ColorCrimson
	ColorDarkBlue             = widgets.ColorDarkBlue
	ColorDarkCyan             = widgets.ColorDarkCyan
	ColorDarkGoldenrod        = widgets.ColorDarkGoldenrod
	ColorDarkGray             = widgets.ColorDarkGray
	ColorDarkGreen            = widgets.ColorDarkGreen
	ColorDarkKhaki            = widgets.ColorDarkKhaki
	ColorDarkMagenta          = widgets.ColorDarkMagenta
	ColorDarkOliveGreen       = widgets.ColorDarkOliveGreen
	ColorDarkOrange           = widgets.ColorDarkOrange
	ColorDarkOrchid           = widgets.ColorDarkOrchid
	ColorDarkRed              = widgets.ColorDarkRed
	ColorDarkSalmon           = widgets.ColorDarkSalmon
	ColorDarkSeaGreen         = widgets.ColorDarkSeaGreen
	ColorDarkSlateBlue        = widgets.ColorDarkSlateBlue
	ColorDarkSlateGray        = widgets.ColorDarkSlateGray
	ColorDarkTurquoise        = widgets.ColorDarkTurquoise
	ColorDarkViolet           = widgets.ColorDarkViolet
	ColorDeepSkyBlue          = widgets.ColorDeepSkyBlue
	ColorDimGray              = widgets.ColorDimGray
	ColorDodgerBlue           = widgets.ColorDodgerBlue
	ColorFirebrick            = widgets.ColorFirebrick
	ColorFloralWhite          = widgets.ColorFloralWhite
	ColorForestGreen          = widgets.ColorForestGreen
	ColorFuchsia              = widgets.ColorFuchsia
	ColorGainsboro            = widgets.ColorGainsboro
	ColorGhostWhite           = widgets.ColorGhostWhite
	ColorGold                 = widgets.ColorGold
	ColorGoldenrod            = widgets.ColorGoldenrod
	ColorGreenYellow          = widgets.ColorGreenYellow
	ColorHoneydew             = widgets.ColorHoneydew
	ColorHotPink              = widgets.ColorHotPink
	ColorIndianRed            = widgets.ColorIndianRed
	ColorIvory                = widgets.ColorIvory
	ColorKhaki                = widgets.ColorKhaki
	ColorLavender             = widgets.ColorLavender
	ColorLavenderBlush        = widgets.ColorLavenderBlush
	ColorLawnGreen            = widgets.ColorLawnGreen
	ColorLemonChiffon         = widgets.ColorLemonChiffon
	ColorLightCoral           = widgets.ColorLightCoral
	ColorLightCyan            = widgets.ColorLightCyan
	ColorLightGoldenrodYellow = widgets.ColorLightGoldenrodYellow
	ColorLightGray            = widgets.ColorLightGray
	ColorLightPink            = widgets.ColorLightPink
	ColorLightSalmon          = widgets.ColorLightSalmon
	ColorLightSeaGreen        = widgets.ColorLightSeaGreen
	ColorLightSkyBlue         = widgets.ColorLightSkyBlue
	ColorLightSlateGray       = widgets.ColorLightSlateGray
	ColorLightSteelBlue       = widgets.ColorLightSteelBlue
	ColorLightYellow          = widgets.ColorLightYellow
	ColorLimeGreen            = widgets.ColorLimeGreen
	ColorLinen                = widgets.ColorLinen
	ColorMagenta              = widgets.ColorMagenta
	ColorMaroon               = widgets.ColorMaroon
	ColorMediumAquamarine     = widgets.ColorMediumAquamarine
	ColorMediumBlue           = widgets.ColorMediumBlue
	ColorMediumOrchid         = widgets.ColorMediumOrchid
	ColorMediumPurple         = widgets.ColorMediumPurple
	ColorMediumSeaGreen       = widgets.ColorMediumSeaGreen
	ColorMediumSlateBlue      = widgets.ColorMediumSlateBlue
	ColorMediumSpringGreen    = widgets.ColorMediumSpringGreen
	ColorMediumTurquoise      = widgets.ColorMediumTurquoise
	ColorMediumVioletRed      = widgets.ColorMediumVioletRed
	ColorMidnightBlue         = widgets.ColorMidnightBlue
	ColorMintCream            = widgets.ColorMintCream
	ColorMistyRose            = widgets.ColorMistyRose
	ColorMoccasin             = widgets.ColorMoccasin
	ColorNavajoWhite          = widgets.ColorNavajoWhite
	ColorNavy                 = widgets.ColorNavy
	ColorOldLace              = widgets.ColorOldLace
	ColorOlive                = widgets.ColorOlive
	ColorOliveDrab            = widgets.ColorOliveDrab
	ColorOrangeRed            = widgets.ColorOrangeRed
	ColorOrchid               = widgets.ColorOrchid
	ColorPaleGoldenrod        = widgets.ColorPaleGoldenrod
	ColorPaleGreen            = widgets.ColorPaleGreen
	ColorPaleTurquoise        = widgets.ColorPaleTurquoise
	ColorPaleVioletRed        = widgets.ColorPaleVioletRed
	ColorPapayaWhip           = widgets.ColorPapayaWhip
	ColorPeachPuff            = widgets.ColorPeachPuff
	ColorPeru                 = widgets.ColorPeru
	ColorPlum                 = widgets.ColorPlum
	ColorPowderBlue           = widgets.ColorPowderBlue
	ColorRebeccaPurple        = widgets.ColorRebeccaPurple
	ColorRosyBrown            = widgets.ColorRosyBrown
	ColorRoyalBlue            = widgets.ColorRoyalBlue
	ColorSaddleBrown          = widgets.ColorSaddleBrown
	ColorSalmon               = widgets.ColorSalmon
	ColorSandyBrown           = widgets.ColorSandyBrown
	ColorSeaGreen             = widgets.ColorSeaGreen
	ColorSeashell             = widgets.ColorSeashell
	ColorSienna               = widgets.ColorSienna
	ColorSilver               = widgets.ColorSilver
	ColorSkyBlue              = widgets.ColorSkyBlue
	ColorSlateBlue            = widgets.ColorSlateBlue
	ColorSlateGray            = widgets.ColorSlateGray
	ColorSnow                 = widgets.ColorSnow
	ColorSpringGreen          = widgets.ColorSpringGreen
	ColorSteelBlue            = widgets.ColorSteelBlue
	ColorTan                  = widgets.ColorTan
	ColorThistle              = widgets.ColorThistle
	ColorTomato               = widgets.ColorTomato
	ColorTurquoise            = widgets.ColorTurquoise
	ColorViolet               = widgets.ColorViolet
	ColorWheat                = widgets.ColorWheat
	ColorWhiteSmoke           = widgets.ColorWhiteSmoke
	ColorYellowGreen          = widgets.ColorYellowGreen

	// Additional Utility Colors
	ColorSuccess   = widgets.ColorSuccess
	ColorInfo      = widgets.ColorInfo
	ColorWarning   = widgets.ColorWarning
	ColorDanger    = widgets.ColorDanger
	ColorLight     = widgets.ColorLight
	ColorDark      = widgets.ColorDark
	ColorMuted     = widgets.ColorMuted
	ColorPrimary   = widgets.ColorPrimary
	ColorSecondary = widgets.ColorSecondary

	// Semantic Colors
	ColorError        = widgets.ColorError
	ColorAlert        = widgets.ColorAlert
	ColorNotification = widgets.ColorNotification
	ColorHighlight    = widgets.ColorHighlight
	ColorDisabled     = widgets.ColorDisabled
	ColorPlaceholder  = widgets.ColorPlaceholder
	ColorDivider      = widgets.ColorDivider
	ColorSurface      = widgets.ColorSurface
	ColorBackground   = widgets.ColorBackground
	ColorOnSurface    = widgets.ColorOnSurface
	ColorOnBackground = widgets.ColorOnBackground
	ColorOnPrimary    = widgets.ColorOnPrimary
	ColorOnSecondary  = widgets.ColorOnSecondary
	ColorOnError      = widgets.ColorOnError

	// Pastel Colors
	ColorPastelRed     = widgets.ColorPastelRed
	ColorPastelOrange  = widgets.ColorPastelOrange
	ColorPastelYellow  = widgets.ColorPastelYellow
	ColorPastelGreen   = widgets.ColorPastelGreen
	ColorPastelBlue    = widgets.ColorPastelBlue
	ColorPastelPurple  = widgets.ColorPastelPurple
	ColorPastelPink    = widgets.ColorPastelPink
	ColorPastelCyan    = widgets.ColorPastelCyan
	ColorPastelLime    = widgets.ColorPastelLime
	ColorPastelMagenta = widgets.ColorPastelMagenta

	// Neon Colors
	ColorNeonRed     = widgets.ColorNeonRed
	ColorNeonOrange  = widgets.ColorNeonOrange
	ColorNeonYellow  = widgets.ColorNeonYellow
	ColorNeonGreen   = widgets.ColorNeonGreen
	ColorNeonBlue    = widgets.ColorNeonBlue
	ColorNeonPurple  = widgets.ColorNeonPurple
	ColorNeonPink    = widgets.ColorNeonPink
	ColorNeonCyan    = widgets.ColorNeonCyan
	ColorNeonLime    = widgets.ColorNeonLime
	ColorNeonMagenta = widgets.ColorNeonMagenta

	// Earth Tones
	ColorEarthBrown      = widgets.ColorEarthBrown
	ColorEarthTan        = widgets.ColorEarthTan
	ColorEarthBeige      = widgets.ColorEarthBeige
	ColorEarthOlive      = widgets.ColorEarthOlive
	ColorEarthForest     = widgets.ColorEarthForest
	ColorEarthSage       = widgets.ColorEarthSage
	ColorEarthTerracotta = widgets.ColorEarthTerracotta
	ColorEarthSienna     = widgets.ColorEarthSienna
	ColorEarthUmber      = widgets.ColorEarthUmber
	ColorEarthOchre      = widgets.ColorEarthOchre

	// Jewel Tones
	ColorJewelRuby      = widgets.ColorJewelRuby
	ColorJewelEmerald   = widgets.ColorJewelEmerald
	ColorJewelSapphire  = widgets.ColorJewelSapphire
	ColorJewelAmethyst  = widgets.ColorJewelAmethyst
	ColorJewelTopaz     = widgets.ColorJewelTopaz
	ColorJewelGarnet    = widgets.ColorJewelGarnet
	ColorJewelTurquoise = widgets.ColorJewelTurquoise
	ColorJewelOpal      = widgets.ColorJewelOpal
	ColorJewelPearl     = widgets.ColorJewelPearl
	ColorJewelOnyx      = widgets.ColorJewelOnyx

	// Metallic Colors
	ColorMetallicGold     = widgets.ColorMetallicGold
	ColorMetallicSilver   = widgets.ColorMetallicSilver
	ColorMetallicCopper   = widgets.ColorMetallicCopper
	ColorMetallicBronze   = widgets.ColorMetallicBronze
	ColorMetallicPlatinum = widgets.ColorMetallicPlatinum
	ColorMetallicChrome   = widgets.ColorMetallicChrome
	ColorMetallicTitanium = widgets.ColorMetallicTitanium
	ColorMetallicSteel    = widgets.ColorMetallicSteel
	ColorMetallicIron     = widgets.ColorMetallicIron
	ColorMetallicLead     = widgets.ColorMetallicLead

	// Vintage Colors
	ColorVintageRose     = widgets.ColorVintageRose
	ColorVintageBlush    = widgets.ColorVintageBlush
	ColorVintagePeach    = widgets.ColorVintagePeach
	ColorVintageApricot  = widgets.ColorVintageApricot
	ColorVintageMint     = widgets.ColorVintageMint
	ColorVintageSage     = widgets.ColorVintageSage
	ColorVintageNavy     = widgets.ColorVintageNavy
	ColorVintageBurgundy = widgets.ColorVintageBurgundy
	ColorVintageMaroon   = widgets.ColorVintageMaroon
	ColorVintageOlive    = widgets.ColorVintageOlive

	// Modern UI Colors
	ColorModernBlue   = widgets.ColorModernBlue
	ColorModernGreen  = widgets.ColorModernGreen
	ColorModernYellow = widgets.ColorModernYellow
	ColorModernRed    = widgets.ColorModernRed
	ColorModernPurple = widgets.ColorModernPurple
	ColorModernTeal   = widgets.ColorModernTeal
	ColorModernOrange = widgets.ColorModernOrange
	ColorModernPink   = widgets.ColorModernPink
	ColorModernIndigo = widgets.ColorModernIndigo
	ColorModernCyan   = widgets.ColorModernCyan

	// Gradient Start/End Colors
	ColorGradientSunrise1 = widgets.ColorGradientSunrise1
	ColorGradientSunrise2 = widgets.ColorGradientSunrise2
	ColorGradientSunset1  = widgets.ColorGradientSunset1
	ColorGradientSunset2  = widgets.ColorGradientSunset2
	ColorGradientOcean1   = widgets.ColorGradientOcean1
	ColorGradientOcean2   = widgets.ColorGradientOcean2
	ColorGradientForest1  = widgets.ColorGradientForest1
	ColorGradientForest2  = widgets.ColorGradientForest2
	ColorGradientFire1    = widgets.ColorGradientFire1
	ColorGradientFire2    = widgets.ColorGradientFire2

	// Icon constants - Action Icons
	IconAdd                   = widgets.IconAdd
	IconAddCircle             = widgets.IconAddCircle
	IconAddCircleOutline      = widgets.IconAddCircleOutline
	IconRemove                = widgets.IconRemove
	IconRemoveCircle          = widgets.IconRemoveCircle
	IconRemoveCircleOutline   = widgets.IconRemoveCircleOutline
	IconEdit                  = widgets.IconEdit
	IconDelete                = widgets.IconDelete
	IconDeleteForever         = widgets.IconDeleteForever
	IconSave                  = widgets.IconSave
	IconCancel                = widgets.IconCancel
	IconClose                 = widgets.IconClose
	IconDone                  = widgets.IconDone
	IconCheck                 = widgets.IconCheck
	IconCheckCircle           = widgets.IconCheckCircle
	IconClear                 = widgets.IconClear
	IconRefresh               = widgets.IconRefresh
	IconUndo                  = widgets.IconUndo
	IconRedo                  = widgets.IconRedo
	IconCopy                  = widgets.IconCopy
	IconPaste                 = widgets.IconPaste
	IconCut                   = widgets.IconCut
	IconSelectAll             = widgets.IconSelectAll
	IconSearch                = widgets.IconSearch
	IconFilter                = widgets.IconFilter
	IconSort                  = widgets.IconSort
	IconPrint                 = widgets.IconPrint
	IconDownload              = widgets.IconDownload
	IconUpload                = widgets.IconUpload
	IconShare                 = widgets.IconShare
	IconFavorite              = widgets.IconFavorite
	IconFavoriteBorder        = widgets.IconFavoriteBorder
	IconBookmark              = widgets.IconBookmark
	IconBookmarkBorder        = widgets.IconBookmarkBorder
	IconStar                  = widgets.IconStar
	IconStarBorder            = widgets.IconStarBorder
	IconStarHalf              = widgets.IconStarHalf
	IconThumbUp               = widgets.IconThumbUp
	IconThumbDown             = widgets.IconThumbDown
	IconLock                  = widgets.IconLock
	IconLockOpen              = widgets.IconLockOpen
	IconVisibility            = widgets.IconVisibility
	IconVisibilityOff         = widgets.IconVisibilityOff
	IconSettings              = widgets.IconSettings
	IconMoreVert              = widgets.IconMoreVert
	IconMoreHoriz             = widgets.IconMoreHoriz
	IconMenu                  = widgets.IconMenu
	IconApps                  = widgets.IconApps
	IconDashboard             = widgets.IconDashboard
	IconWidgets               = widgets.IconWidgets
	IconExtension             = widgets.IconExtension
	IconPower                 = widgets.IconPower
	IconPowerOff              = widgets.IconPowerOff
	IconRestart               = widgets.IconRestart
	IconUpdate                = widgets.IconUpdate
	IconSync                  = widgets.IconSync
	IconSyncAlt               = widgets.IconSyncAlt
	IconAutorenew             = widgets.IconAutorenew
	IconCached                = widgets.IconCached
	IconBackup                = widgets.IconBackup
	IconRestore               = widgets.IconRestore
	IconHistory               = widgets.IconHistory
	IconSchedule              = widgets.IconSchedule
	IconTimer                 = widgets.IconTimer
	IconAlarm                 = widgets.IconAlarm
	IconAlarmOn               = widgets.IconAlarmOn
	IconAlarmOff              = widgets.IconAlarmOff
	IconNotifications         = widgets.IconNotifications
	IconNotificationsOff      = widgets.IconNotificationsOff
	IconNotificationsActive   = widgets.IconNotificationsActive
	IconNotificationsPaused   = widgets.IconNotificationsPaused
	IconInfo                  = widgets.IconInfo
	IconInfoOutline           = widgets.IconInfoOutline
	IconWarning               = widgets.IconWarning
	IconError                 = widgets.IconError
	IconErrorOutline          = widgets.IconErrorOutline
	IconHelp                  = widgets.IconHelp
	IconHelpOutline           = widgets.IconHelpOutline
	IconFeedback              = widgets.IconFeedback
	IconBug                   = widgets.IconBug
	IconCode                  = widgets.IconCode
	IconDeveloperMode         = widgets.IconDeveloperMode
	IconBuild                 = widgets.IconBuild
	IconConstruction          = widgets.IconConstruction
	IconHandyman              = widgets.IconHandyman
	IconEngineering           = widgets.IconEngineering
	IconScience               = widgets.IconScience
	IconBiotech               = widgets.IconBiotech
	IconPsychology            = widgets.IconPsychology
	IconSchool                = widgets.IconSchool
	IconLibraryBooks          = widgets.IconLibraryBooks
	IconBook                  = widgets.IconBook
	IconMenuBook              = widgets.IconMenuBook
	IconAutoStories           = widgets.IconAutoStories
	IconImportContacts        = widgets.IconImportContacts
	IconClass                 = widgets.IconClass
	IconGrade                 = widgets.IconGrade
	IconAssignment            = widgets.IconAssignment
	IconAssignmentInd         = widgets.IconAssignmentInd
	IconAssignmentLate        = widgets.IconAssignmentLate
	IconAssignmentReturn      = widgets.IconAssignmentReturn
	IconAssignmentReturned    = widgets.IconAssignmentReturned
	IconAssignmentTurnedIn    = widgets.IconAssignmentTurnedIn
	IconQuiz                  = widgets.IconQuiz
	IconLiveHelp              = widgets.IconLiveHelp
	IconContactSupport        = widgets.IconContactSupport
	IconSupportAgent          = widgets.IconSupportAgent
	IconHeadset               = widgets.IconHeadset
	IconHeadsetMic            = widgets.IconHeadsetMic
	IconMic                   = widgets.IconMic
	IconMicOff                = widgets.IconMicOff
	IconMicNone               = widgets.IconMicNone
	IconKeyboard              = widgets.IconKeyboard
	IconKeyboardArrowDown     = widgets.IconKeyboardArrowDown
	IconKeyboardArrowLeft     = widgets.IconKeyboardArrowLeft
	IconKeyboardArrowRight    = widgets.IconKeyboardArrowRight
	IconKeyboardArrowUp       = widgets.IconKeyboardArrowUp
	IconKeyboardBackspace     = widgets.IconKeyboardBackspace
	IconKeyboardCapslock      = widgets.IconKeyboardCapslock
	IconKeyboardHide          = widgets.IconKeyboardHide
	IconKeyboardReturn        = widgets.IconKeyboardReturn
	IconKeyboardTab           = widgets.IconKeyboardTab
	IconKeyboardVoice         = widgets.IconKeyboardVoice
	IconSpaceBar              = widgets.IconSpaceBar
	IconMouse                 = widgets.IconMouse
	IconTouchApp              = widgets.IconTouchApp
	IconGesture               = widgets.IconGesture
	IconPan                   = widgets.IconPan
	IconZoomIn                = widgets.IconZoomIn
	IconZoomOut               = widgets.IconZoomOut
	IconZoomOutMap            = widgets.IconZoomOutMap
	IconCenterFocusStrong     = widgets.IconCenterFocusStrong
	IconCenterFocusWeak       = widgets.IconCenterFocusWeak
	IconCrop                  = widgets.IconCrop
	IconCropFree              = widgets.IconCropFree
	IconCropOriginal          = widgets.IconCropOriginal
	IconCropSquare            = widgets.IconCropSquare
	IconCrop169               = widgets.IconCrop169
	IconCrop32                = widgets.IconCrop32
	IconCrop54                = widgets.IconCrop54
	IconCrop75                = widgets.IconCrop75
	IconCropDin               = widgets.IconCropDin
	IconCropLandscape         = widgets.IconCropLandscape
	IconCropPortrait          = widgets.IconCropPortrait
	IconRotateLeft            = widgets.IconRotateLeft
	IconRotateRight           = widgets.IconRotateRight
	IconRotate90DegreesCcw    = widgets.IconRotate90DegreesCcw
	IconFlipToBack            = widgets.IconFlipToBack
	IconFlipToFront           = widgets.IconFlipToFront
	IconFlip                  = widgets.IconFlip
	IconTransform             = widgets.IconTransform
	IconStraighten            = widgets.IconStraighten
	IconTune                  = widgets.IconTune
	IconPalette               = widgets.IconPalette
	IconColorize              = widgets.IconColorize
	IconBrush                 = widgets.IconBrush
	IconFormatPaint           = widgets.IconFormatPaint
	IconFormatColorFill       = widgets.IconFormatColorFill
	IconFormatColorReset      = widgets.IconFormatColorReset
	IconFormatColorText       = widgets.IconFormatColorText
	IconInvertColors          = widgets.IconInvertColors
	IconInvertColorsOff       = widgets.IconInvertColorsOff
	IconGradient              = widgets.IconGradient
	IconTexture               = widgets.IconTexture
	IconBlur                  = widgets.IconBlur
	IconBlurCircular          = widgets.IconBlurCircular
	IconBlurLinear            = widgets.IconBlurLinear
	IconBlurOff               = widgets.IconBlurOff
	IconBlurOn                = widgets.IconBlurOn
	IconBrightness1           = widgets.IconBrightness1
	IconBrightness2           = widgets.IconBrightness2
	IconBrightness3           = widgets.IconBrightness3
	IconBrightness4           = widgets.IconBrightness4
	IconBrightness5           = widgets.IconBrightness5
	IconBrightness6           = widgets.IconBrightness6
	IconBrightness7           = widgets.IconBrightness7
	IconBrightnessAuto        = widgets.IconBrightnessAuto
	IconBrightnessHigh        = widgets.IconBrightnessHigh
	IconBrightnessLow         = widgets.IconBrightnessLow
	IconBrightnessMedium      = widgets.IconBrightnessMedium
	IconContrast              = widgets.IconContrast
	IconExposure              = widgets.IconExposure
	IconExposureNeg1          = widgets.IconExposureNeg1
	IconExposureNeg2          = widgets.IconExposureNeg2
	IconExposurePlus1         = widgets.IconExposurePlus1
	IconExposurePlus2         = widgets.IconExposurePlus2
	IconExposureZero          = widgets.IconExposureZero
	IconWbAuto                = widgets.IconWbAuto
	IconWbCloudy              = widgets.IconWbCloudy
	IconWbIncandescent        = widgets.IconWbIncandescent
	IconWbIridescent          = widgets.IconWbIridescent
	IconWbShade               = widgets.IconWbShade
	IconWbSunny               = widgets.IconWbSunny
	IconWbTwilight            = widgets.IconWbTwilight
	IconFlare                 = widgets.IconFlare
	IconLensBlur              = widgets.IconLensBlur
	IconPhotoFilter           = widgets.IconPhotoFilter
	IconVignette              = widgets.IconVignette
	IconDetails               = widgets.IconDetails
	IconLooks                 = widgets.IconLooks
	IconLooks3                = widgets.IconLooks3
	IconLooks4                = widgets.IconLooks4
	IconLooks5                = widgets.IconLooks5
	IconLooks6                = widgets.IconLooks6
	IconLooksOne              = widgets.IconLooksOne
	IconLooksTwo              = widgets.IconLooksTwo
	IconMonochromePhotos      = widgets.IconMonochromePhotos
	IconNature                = widgets.IconNature
	IconNaturePeople          = widgets.IconNaturePeople
	IconPortrait              = widgets.IconPortrait
	IconTagFaces              = widgets.IconTagFaces
	IconTimelapse             = widgets.IconTimelapse
	IconTimer10               = widgets.IconTimer10
	IconTimer3                = widgets.IconTimer3
	IconTimerOff              = widgets.IconTimerOff
	IconTonality              = widgets.IconTonality
	IconViewComfy             = widgets.IconViewComfy
	IconViewCompact           = widgets.IconViewCompact
	IconViewModule            = widgets.IconViewModule
	IconViewQuilt             = widgets.IconViewQuilt
	IconViewStream            = widgets.IconViewStream
	IconViewWeek              = widgets.IconViewWeek
	IconViewDay               = widgets.IconViewDay
	IconViewAgenda            = widgets.IconViewAgenda
	IconViewArray             = widgets.IconViewArray
	IconViewCarousel          = widgets.IconViewCarousel
	IconViewColumn            = widgets.IconViewColumn
	IconViewHeadline          = widgets.IconViewHeadline
	IconViewList              = widgets.IconViewList
	IconViewSidebar           = widgets.IconViewSidebar
	IconGridOn                = widgets.IconGridOn
	IconGridOff               = widgets.IconGridOff
	IconGrid3x3               = widgets.IconGrid3x3
	IconGrid4x4               = widgets.IconGrid4x4
	IconGridGoldenratio       = widgets.IconGridGoldenratio
	IconImage                 = widgets.IconImage
	IconImageAspectRatio      = widgets.IconImageAspectRatio
	IconImageNotSupported     = widgets.IconImageNotSupported
	IconImageSearch           = widgets.IconImageSearch
	IconBrokenImage           = widgets.IconBrokenImage
	IconCollections           = widgets.IconCollections
	IconCollectionsBookmark   = widgets.IconCollectionsBookmark
	IconColorLens             = widgets.IconColorLens
	IconCompare               = widgets.IconCompare
	IconControlPoint          = widgets.IconControlPoint
	IconControlPointDuplicate = widgets.IconControlPointDuplicate
	IconMovie                 = widgets.IconMovie
	IconMovieCreation         = widgets.IconMovieCreation
	IconMovieFilter           = widgets.IconMovieFilter
	IconMusicNote             = widgets.IconMusicNote
	IconMusicVideo            = widgets.IconMusicVideo
	IconAudiotrack            = widgets.IconAudiotrack
	IconAlbum                 = widgets.IconAlbum
	IconArtTrack              = widgets.IconArtTrack
	IconAvTimer               = widgets.IconAvTimer
	IconBrandingWatermark     = widgets.IconBrandingWatermark
	IconCallToAction          = widgets.IconCallToAction
	IconClosedCaption         = widgets.IconClosedCaption
	IconEqualizer             = widgets.IconEqualizer
	IconExplicit              = widgets.IconExplicit
	IconFastForward           = widgets.IconFastForward
	IconFastRewind            = widgets.IconFastRewind
	IconForward10             = widgets.IconForward10
	IconForward30             = widgets.IconForward30
	IconForward5              = widgets.IconForward5
	IconGames                 = widgets.IconGames
	IconHd                    = widgets.IconHd
	IconHearing               = widgets.IconHearing
	IconHighQuality           = widgets.IconHighQuality
	IconLibraryAdd            = widgets.IconLibraryAdd
	IconLibraryMusic          = widgets.IconLibraryMusic
	IconLoop                  = widgets.IconLoop
	IconNote                  = widgets.IconNote
	IconPause                 = widgets.IconPause
	IconPauseCircleFilled     = widgets.IconPauseCircleFilled
	IconPauseCircleOutline    = widgets.IconPauseCircleOutline
	IconPlayArrow             = widgets.IconPlayArrow
	IconPlayCircleFilled      = widgets.IconPlayCircleFilled
	IconPlayCircleOutline     = widgets.IconPlayCircleOutline
	IconPlaylistAdd           = widgets.IconPlaylistAdd
	IconPlaylistAddCheck      = widgets.IconPlaylistAddCheck
	IconPlaylistPlay          = widgets.IconPlaylistPlay
	IconQueue                 = widgets.IconQueue
	IconQueueMusic            = widgets.IconQueueMusic
	IconQueuePlayNext         = widgets.IconQueuePlayNext
	IconRadio                 = widgets.IconRadio
	IconRecentActors          = widgets.IconRecentActors
	IconRemoveFromQueue       = widgets.IconRemoveFromQueue
	IconRepeat                = widgets.IconRepeat
	IconRepeatOne             = widgets.IconRepeatOne
	IconReplay                = widgets.IconReplay
	IconReplay10              = widgets.IconReplay10
	IconReplay30              = widgets.IconReplay30
	IconReplay5               = widgets.IconReplay5
	IconShuffle               = widgets.IconShuffle
	IconSkipNext              = widgets.IconSkipNext
	IconSkipPrevious          = widgets.IconSkipPrevious
	IconSnooze                = widgets.IconSnooze
	IconSortByAlpha           = widgets.IconSortByAlpha
	IconStop                  = widgets.IconStop
	IconSubscriptions         = widgets.IconSubscriptions
	IconSubtitles             = widgets.IconSubtitles
	IconSurroundSound         = widgets.IconSurroundSound
	IconVideoCall             = widgets.IconVideoCall
	IconVideoLabel            = widgets.IconVideoLabel
	IconVideoLibrary          = widgets.IconVideoLibrary
	IconVideocam              = widgets.IconVideocam
	IconVideocamOff           = widgets.IconVideocamOff
	IconVolumeDown            = widgets.IconVolumeDown
	IconVolumeMute            = widgets.IconVolumeMute
	IconVolumeOff             = widgets.IconVolumeOff
	IconVolumeUp              = widgets.IconVolumeUp
	IconWeb                   = widgets.IconWeb
	IconWebAsset              = widgets.IconWebAsset

	// Navigation Icons
	IconArrowBack                = widgets.IconArrowBack
	IconArrowForward             = widgets.IconArrowForward
	IconArrowUpward              = widgets.IconArrowUpward
	IconArrowDownward            = widgets.IconArrowDownward
	IconArrowLeft                = widgets.IconArrowLeft
	IconArrowRight               = widgets.IconArrowRight
	IconArrowUp                  = widgets.IconArrowUp
	IconArrowDown                = widgets.IconArrowDown
	IconArrowBackIos             = widgets.IconArrowBackIos
	IconArrowForwardIos          = widgets.IconArrowForwardIos
	IconChevronLeft              = widgets.IconChevronLeft
	IconChevronRight             = widgets.IconChevronRight
	IconExpandLess               = widgets.IconExpandLess
	IconExpandMore               = widgets.IconExpandMore
	IconFirstPage                = widgets.IconFirstPage
	IconLastPage                 = widgets.IconLastPage
	IconFullscreen               = widgets.IconFullscreen
	IconFullscreenExit           = widgets.IconFullscreenExit
	IconSubdirectoryArrowLeft    = widgets.IconSubdirectoryArrowLeft
	IconSubdirectoryArrowRight   = widgets.IconSubdirectoryArrowRight
	IconUnfoldLess               = widgets.IconUnfoldLess
	IconUnfoldMore               = widgets.IconUnfoldMore
	IconSwitchLeft               = widgets.IconSwitchLeft
	IconSwitchRight              = widgets.IconSwitchRight
	IconDoubleArrow              = widgets.IconDoubleArrow
	IconKeyboardDoubleArrowLeft  = widgets.IconKeyboardDoubleArrowLeft
	IconKeyboardDoubleArrowRight = widgets.IconKeyboardDoubleArrowRight
	IconKeyboardDoubleArrowUp    = widgets.IconKeyboardDoubleArrowUp
	IconKeyboardDoubleArrowDown  = widgets.IconKeyboardDoubleArrowDown
	IconNorthEast                = widgets.IconNorthEast
	IconNorthWest                = widgets.IconNorthWest
	IconSouthEast                = widgets.IconSouthEast
	IconSouthWest                = widgets.IconSouthWest
	IconEast                     = widgets.IconEast
	IconWest                     = widgets.IconWest
	IconNorth                    = widgets.IconNorth
	IconSouth                    = widgets.IconSouth

	// Communication Icons
	IconCall                      = widgets.IconCall
	IconCallEnd                   = widgets.IconCallEnd
	IconCallMade                  = widgets.IconCallMade
	IconCallMissed                = widgets.IconCallMissed
	IconCallReceived              = widgets.IconCallReceived
	IconCallSplit                 = widgets.IconCallSplit
	IconCellWifi                  = widgets.IconCellWifi
	IconChatBubble                = widgets.IconChatBubble
	IconChatBubbleOutline         = widgets.IconChatBubbleOutline
	IconClearAll                  = widgets.IconClearAll
	IconComment                   = widgets.IconComment
	IconContactMail               = widgets.IconContactMail
	IconContactPhone              = widgets.IconContactPhone
	IconContacts                  = widgets.IconContacts
	IconDialerSip                 = widgets.IconDialerSip
	IconDialpad                   = widgets.IconDialpad
	IconEmail                     = widgets.IconEmail
	IconForum                     = widgets.IconForum
	IconImportExport              = widgets.IconImportExport
	IconLocationOff               = widgets.IconLocationOff
	IconLocationOn                = widgets.IconLocationOn
	IconMailOutline               = widgets.IconMailOutline
	IconMessage                   = widgets.IconMessage
	IconNoSim                     = widgets.IconNoSim
	IconPhone                     = widgets.IconPhone
	IconPhonelinkErase            = widgets.IconPhonelinkErase
	IconPhonelinkLock             = widgets.IconPhonelinkLock
	IconPhonelinkRing             = widgets.IconPhonelinkRing
	IconPhonelinkSetup            = widgets.IconPhonelinkSetup
	IconPortableWifiOff           = widgets.IconPortableWifiOff
	IconPresentToAll              = widgets.IconPresentToAll
	IconRingVolume                = widgets.IconRingVolume
	IconRssFeed                   = widgets.IconRssFeed
	IconScreenShare               = widgets.IconScreenShare
	IconSpeakerPhone              = widgets.IconSpeakerPhone
	IconStayCurrentLandscape      = widgets.IconStayCurrentLandscape
	IconStayCurrentPortrait       = widgets.IconStayCurrentPortrait
	IconStayPrimaryLandscape      = widgets.IconStayPrimaryLandscape
	IconStayPrimaryPortrait       = widgets.IconStayPrimaryPortrait
	IconStopScreenShare           = widgets.IconStopScreenShare
	IconSwapCalls                 = widgets.IconSwapCalls
	IconTextsms                   = widgets.IconTextsms
	IconVoicemail                 = widgets.IconVoicemail
	IconVpnKey                    = widgets.IconVpnKey
	IconAlternateEmail            = widgets.IconAlternateEmail
	IconBusiness                  = widgets.IconBusiness
	IconCallMissedOutgoing        = widgets.IconCallMissedOutgoing
	IconCancelPresentation        = widgets.IconCancelPresentation
	IconDesktopAccessDisabled     = widgets.IconDesktopAccessDisabled
	IconDuo                       = widgets.IconDuo
	IconMobileScreenShare         = widgets.IconMobileScreenShare
	IconMoreTime                  = widgets.IconMoreTime
	IconNat                       = widgets.IconNat
	IconPersonAddDisabled         = widgets.IconPersonAddDisabled
	IconPersonSearch              = widgets.IconPersonSearch
	IconPhoneCallback             = widgets.IconPhoneCallback
	IconPhoneForwarded            = widgets.IconPhoneForwarded
	IconPhoneInTalk               = widgets.IconPhoneInTalk
	IconPhoneLocked               = widgets.IconPhoneLocked
	IconPhoneMissed               = widgets.IconPhoneMissed
	IconPhonePaused               = widgets.IconPhonePaused
	IconPrintDisabled             = widgets.IconPrintDisabled
	IconQrCode                    = widgets.IconQrCode
	IconQrCode2                   = widgets.IconQrCode2
	IconQrCodeScanner             = widgets.IconQrCodeScanner
	IconReadMore                  = widgets.IconReadMore
	IconSentimentDissatisfied     = widgets.IconSentimentDissatisfied
	IconSentimentNeutral          = widgets.IconSentimentNeutral
	IconSentimentSatisfied        = widgets.IconSentimentSatisfied
	IconSentimentVeryDissatisfied = widgets.IconSentimentVeryDissatisfied
	IconSentimentVerySatisfied    = widgets.IconSentimentVerySatisfied
	IconSpeakerNotes              = widgets.IconSpeakerNotes
	IconSpeakerNotesOff           = widgets.IconSpeakerNotesOff
	IconUnsubscribe               = widgets.IconUnsubscribe
	IconMarkChatRead              = widgets.IconMarkChatRead
	IconMarkChatUnread            = widgets.IconMarkChatUnread
	IconMarkEmailRead             = widgets.IconMarkEmailRead
	IconMarkEmailUnread           = widgets.IconMarkEmailUnread

	// Content Icons
	IconAddBox       = widgets.IconAddBox
	IconArchive      = widgets.IconArchive
	IconBackspace    = widgets.IconBackspace
	IconBlock        = widgets.IconBlock
	IconContent      = widgets.IconContent
	IconContentCopy  = widgets.IconContentCopy
	IconContentCut   = widgets.IconContentCut
	IconContentPaste = widgets.IconContentPaste
	IconCreate       = widgets.IconCreate
	IconDeleteSweep  = widgets.IconDeleteSweep
	IconDrafts       = widgets.IconDrafts
	IconFilterList   = widgets.IconFilterList
	IconFlag         = widgets.IconFlag
	IconFontDownload = widgets.IconFontDownload
	IconForward      = widgets.IconForward
	IconInbox        = widgets.IconInbox
	IconLink         = widgets.IconLink
	IconLinkOff      = widgets.IconLinkOff
	IconLowPriority  = widgets.IconLowPriority
	IconMail         = widgets.IconMail
	IconMarkunread   = widgets.IconMarkunread
	IconMoveToInbox  = widgets.IconMoveToInbox
	IconNextWeek     = widgets.IconNextWeek
	IconReport       = widgets.IconReport
	IconReportOff    = widgets.IconReportOff
	IconSend         = widgets.IconSend
	IconUnarchive    = widgets.IconUnarchive
	IconWeekend      = widgets.IconWeekend
	IconWhereToVote  = widgets.IconWhereToVote
	IconBallot       = widgets.IconBallot
	IconCalculate    = widgets.IconCalculate
	IconDynamicFeed  = widgets.IconDynamicFeed
	IconFileCopy     = widgets.IconFileCopy
	IconHowToReg     = widgets.IconHowToReg
	IconHowToVote    = widgets.IconHowToVote
	IconInsights     = widgets.IconInsights
	IconInventory    = widgets.IconInventory
	IconInventory2   = widgets.IconInventory2
	IconOutlinedFlag = widgets.IconOutlinedFlag
	IconPolicy       = widgets.IconPolicy
	IconPushPin      = widgets.IconPushPin
	IconReply        = widgets.IconReply
	IconReplyAll     = widgets.IconReplyAll
	IconSaveAlt      = widgets.IconSaveAlt
	IconShield       = widgets.IconShield
	IconSquareFoot   = widgets.IconSquareFoot
	IconTag          = widgets.IconTag
	IconTextSnippet  = widgets.IconTextSnippet
	IconUpcoming     = widgets.IconUpcoming
	IconWaves        = widgets.IconWaves

	// Device Icons
	IconDevices          = widgets.IconDevices
	IconDevicesOther     = widgets.IconDevicesOther
	IconDeviceHub        = widgets.IconDeviceHub
	IconDeviceUnknown    = widgets.IconDeviceUnknown
	IconDesktopMac       = widgets.IconDesktopMac
	IconDesktopWindows   = widgets.IconDesktopWindows
	IconDeveloperBoard   = widgets.IconDeveloperBoard
	IconDock             = widgets.IconDock
	IconGamepad          = widgets.IconGamepad
	IconHeadphones       = widgets.IconHeadphones
	IconLaptop           = widgets.IconLaptop
	IconLaptopChromebook = widgets.IconLaptopChromebook
	IconLaptopMac        = widgets.IconLaptopMac
	IconLaptopWindows    = widgets.IconLaptopWindows
	IconMemory           = widgets.IconMemory
	IconPhoneAndroid     = widgets.IconPhoneAndroid
	IconPhoneIphone      = widgets.IconPhoneIphone
	IconPhonelink        = widgets.IconPhonelink
	IconPhonelinkOff     = widgets.IconPhonelinkOff
	IconPowerInput       = widgets.IconPowerInput
	IconRouter           = widgets.IconRouter
	IconScanner          = widgets.IconScanner
	IconSecurity         = widgets.IconSecurity
	IconSimCard          = widgets.IconSimCard
	IconSmartphone       = widgets.IconSmartphone
	IconSpeaker          = widgets.IconSpeaker
	IconSpeakerGroup     = widgets.IconSpeakerGroup
	IconTablet           = widgets.IconTablet
	IconTabletAndroid    = widgets.IconTabletAndroid
	IconTabletMac        = widgets.IconTabletMac
	IconToys             = widgets.IconToys
	IconTv               = widgets.IconTv
	IconVideogameAsset   = widgets.IconVideogameAsset
	IconWatch            = widgets.IconWatch
	IconCast             = widgets.IconCast
	IconCastConnected    = widgets.IconCastConnected
	IconComputer         = widgets.IconComputer
	IconConnectedTv      = widgets.IconConnectedTv
	IconKeyboardAlt      = widgets.IconKeyboardAlt
	IconLiveTv           = widgets.IconLiveTv
	IconSmartDisplay     = widgets.IconSmartDisplay
	IconSmartScreen      = widgets.IconSmartScreen
	IconSmartToy         = widgets.IconSmartToy

	// File Icons
	IconFolder             = widgets.IconFolder
	IconFolderOpen         = widgets.IconFolderOpen
	IconFolderShared       = widgets.IconFolderShared
	IconFolderSpecial      = widgets.IconFolderSpecial
	IconCreateNewFolder    = widgets.IconCreateNewFolder
	IconAttachFile         = widgets.IconAttachFile
	IconAttachment         = widgets.IconAttachment
	IconCloud              = widgets.IconCloud
	IconCloudCircle        = widgets.IconCloudCircle
	IconCloudDone          = widgets.IconCloudDone
	IconCloudDownload      = widgets.IconCloudDownload
	IconCloudOff           = widgets.IconCloudOff
	IconCloudQueue         = widgets.IconCloudQueue
	IconCloudUpload        = widgets.IconCloudUpload
	IconFileDownload       = widgets.IconFileDownload
	IconFileUpload         = widgets.IconFileUpload
	IconOfflinePin         = widgets.IconOfflinePin
	IconCloudSync          = widgets.IconCloudSync
	IconDriveFolderUpload  = widgets.IconDriveFolderUpload
	IconUploadFile         = widgets.IconUploadFile
	IconDownloadForOffline = widgets.IconDownloadForOffline
	IconDownloadDone       = widgets.IconDownloadDone
	IconFilePresent        = widgets.IconFilePresent
	IconFolderZip          = widgets.IconFolderZip
	IconRequestQuote       = widgets.IconRequestQuote
	IconRuleFolder         = widgets.IconRuleFolder
	IconSnippetFolder      = widgets.IconSnippetFolder
	IconTopic              = widgets.IconTopic
	IconWorkspaces         = widgets.IconWorkspaces
)
